config/routes.rb
Rails.application.routes.draw do
  resources :question, only: [:show]
  get 'course/index'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :questions 
  validates :name, presence: true, length: { minimun: 5, maximum: 50 }
  validates :description, presence: true, length: { minimun: 10, maximum: 300 }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :course 
  has_many :answers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def index
    @courses = Course.where(id: (Question.distinct.pluck(:course_id)))
  end
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  def show
    # How many questions for this course
    pool_number = Question.where("course_id" => params[:id]).count
    # Randomly select 10 numbers from that pool
    @display_questions = select_random(pool_number, 10)
    
    if @display_questions.kind_of?(Array) 
      # Pull the selected questions, by id, from the database
      @question_list = Question.where("course_id" => params[:id]).where('id IN (?)', @display_questions)
      # Match up the answers with the questions
      @quiz = create_quiz(@question_list)
    end
  end

  private 

  def select_random(total_in_pool, total_items_returned)
    selected_items = []
    # Set a boundary
    if total_items_returned < 1 || total_items_returned > 50
      return -1
    end 
    # Can't request more than we have
    if total_items_returned > total_in_pool
      return -1
    end  
    # Build the array for selected id numbers, remove any duplicates
    while selected_items.length < total_items_returned
      selected_items.push(rand(1..total_in_pool))
      selected_items = selected_items.uniq
    end 

    return selected_items
  end    

  def create_quiz(question_list)
    new_array = []
    # For each selected question...
    question_list.each do |question|
      
      # Available formats: true/false and multiple choice 
      if question.format_type == 0 
        Answer.where("question_id" => question.id).map do |answer_query| 
          # Always display in the same order
          if answer_query.body.downcase.strip  === "true" 
            filler_format = { :k => "true", :m => "false" }
          else
            filler_format = { :m => "true", :k => "false" } 
          end
          # Push the question answer pair to the array
          hash = { :question => question.body, :answer_list => filler_format } 
          new_array.push(hash)
        end
      else 
        multiple_choice = []
        # Push the correct response to the temporary array
        Answer.where("question_id" => question.id).where("correct" => true).map do |answer_query|
          multiple_choice.push(answer_query.body)
        end
        # Get the entire pool of false choices
        answer_filler = Answer.where("question_id" => question.id).where("correct" => false).map do |answer_query|
          answer_query.body 
        end 
        # Randomly select 4 from the false batch and push to the temp array
        selected_answer_filler = select_random(answer_filler.count, 4).each do |index|
          multiple_choice.push(answer_filler[index - 1])
        end
        # Shuffle up the choices and create a single hash array index
        inner_hash = { :k => multiple_choice[0], :e => multiple_choice[1], :d => multiple_choice[2], :n => multiple_choice[3], :a => multiple_choice[4] }.to_a.shuffle
        converted_hash = { 
          inner_hash[0][0] => inner_hash[0][1], 
          inner_hash[1][0] => inner_hash[1][1], 
          inner_hash[2][0] => inner_hash[2][1], 
          inner_hash[3][0] => inner_hash[3][1], 
          inner_hash[4][0] => inner_hash[4][1] }
        # Push the question answer pair to the array
        hash = { :question => question.body, :answer_list => converted_hash }
        new_array.push(hash)
      end
    end
    return new_array
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/course/index.html.erb
<div class="container">
  <div class="row">
    <% @courses.each do |course| %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <%= link_to '<i class="material-icons right">create</i>Take Quiz'.html_safe, question_path(course.id), class: "waves-effect waves-light btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HF Quiz Machine</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
        <div>
        <%= link_to '<i class="material-icons right">grain</i>H.F. Quiz Machine'.html_safe, root_path , class: "waves-effect waves-light btn" %>
        </div>
      </div>
    </header>

    <main class="main-content">
      <%= yield %>
    </main>

    <footer class="page-footer teal">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">Open Source Project</h5>
            <p class="grey-text text-lighten-4">Harold Finch Quiz Machine is open source.  Be a part of the H.F. Quiz Machine community or help improve your favorite quiz application for Web Developers.</p>
            <a class="waves-effect waves-light btn" href="https://github.com/OTR500miles2go">Fork on Github</a>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text right-align">Keep In Touch</h5>
            <ul class="contact-list right-align">
              <li><a class="grey-text text-lighten-3 right-align" href="https://github.com/OTR500miles2go">GitHub</a></li>
              <li><a class="grey-text text-lighten-3 right-align" href="https://www.linkedin.com/in/dianegaydenin/">LinkedIn</a></li>
              <li><a class="grey-text text-lighten-3 right-align" href="https://twitter.com/GaydenDiane">Twitter</a></li>
            </ul>
          </div>
        </div>
      </div>

      <div class="footer-copyright">
        <div class="container center-align">
          <a class="grey-text text-lighten-4 center-align" href="https://www.dianegayden.com">© 2019 Diane Gayden.com</a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/question/show.html.erb
<div class="row">
  <div class="card-panel blue-grey darken-1">
    <div class="blue-grey lighten-5 center-align">
      <h3 class="black-text">Questions: <%= @quiz.count %></h3>
      <h5 class="black-text">Refresh to get a new set of questions.</h5>
    </div>
  </div>
  <div class="container" id="question-page">
    <% @quiz.each_with_index do |item, index| %>
      <% question_number = index + 1 %>
      <form>
        <div class="row">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title center-align">Question: <%= question_number %></span>
              <h5><%= item[:question] %></h5>
            </div>
            <div style="position:relative;width:100%;">
              <div class="card-action white-text" id="altcontainer">
                <p>
                  <% item[:answer_list].each do |key, value|  %>
                    <label class="answer-list">
                    <input type="checkbox" class="radio" value="<%= key %>" name="boxby[<%= question_number %>]" >
                      <span><%= value %></span>
                    </label>
                  <% end %>
                </p>
              </div>
            </div>
            <div class="divider">
              <%# Divider line %>
            </div>
            <div class="card-action">
              <p class="checked-answer yellow-text text-darken-4" id="checked-correct" name="boxby[<%= question_number %>]">That's correct!</p>
              <p class="checked-answer red-text text-darken-4" id="checked-false" name="boxby[<%= question_number %>]">Try again.</p>
            </div>
          </div>
        </div>
      </form>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="mission">
  <h2 class="mission-statement">Be the best Web Developer you can be.</h2>
  <div class="mission-button"><%= link_to '<i class="material-icons right">create</i>Enter'.html_safe, course_index_path , class: "waves-effect waves-light btn" %></div>
</div>